<a href="https://colab.research.google.com/github/WTFjarux/Concepts-and-Technologies-of-AI/blob/main/2438454_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
import numpy as np
a= np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
b = np.array([[1,2,3,5],[4,5,6,7]])
b


array([[1, 2, 3, 5],
       [4, 5, 6, 7]])

In [28]:
c = np.concatenate((a,b),axis=0)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 5],
       [4, 5, 6, 7]])

In [12]:
import numpy as np
a = np . arange (1 , 10)
print ( a )
x = range (1 , 10)
print ( x ) # x is an iterator
print ( list ( x ) )
# further arange examples :
x = np . arange (10.4)
print ( x )
x = np . arange (0.5 , 10.4 , 0.8)
print ( x )

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


TO DO TASKS



4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [35]:
#1
import numpy as np
arr_empty = np.empty((2,2))
arr_empty



array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
#2
arr_ones = np.ones((4,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
#3
arr_full = np.full((4,2),9)
arr_full

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [49]:
#4
arr_zeros = np.zeros_like(arr_empty)
arr_zeros

array([[0., 0.],
       [0., 0.]])

In [50]:
#5
arr_ones_like = np.ones_like(arr_ones)
arr_ones_like

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
#6
new_list = [1,2,3,4]
arr_new_list = np.array(new_list)
arr_new_list

array([1, 2, 3, 4])

4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [52]:
#1
arr_range = np.arange(10,50)
arr_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [53]:
#2
arr_reshape = np.arange(9).reshape(3,3)
arr_reshape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
#3
arr_identity= np.eye(3)
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#4
arr_random= np.random.random(30)
print(arr_random,"\n")
arr_random_mean=np.mean(arr_random)
arr_random_mean

[0.98114438 0.32088786 0.11236804 0.95652149 0.70494462 0.08097538
 0.96264661 0.60291431 0.75203664 0.73612261 0.99067949 0.97925894
 0.93397345 0.10417424 0.86688216 0.64307547 0.65611879 0.61533499
 0.60967429 0.68118562 0.06852437 0.30199248 0.66418913 0.908559
 0.48238102 0.26410175 0.20861594 0.30873344 0.4838381  0.09639029] 



0.5692748302886897

In [88]:
#5
import warnings
warnings.filterwarnings('ignore')
arr_rand=np.random.random_integers(100, size=(10,10))
print(arr_rand)
arr_rand_min=arr_rand.min()
arr_rand_max=arr_rand.max()
print("\nMinimum value:",arr_rand_min)
print("Maximum value:",arr_rand_max)


[[24 35 66 73 28 12 21 17  8 11]
 [16 49 49 99 11 20 70 65 56 24]
 [53 56 32 19 27 37 19 75  9 72]
 [91 64 56 70  9 96 83 91 61 73]
 [86 87 66 58 30 75 60 44 15 75]
 [23 64 69 46 15 28 90 17 48 48]
 [15 22 25 83 68  7 51 69 98 44]
 [62 50 87 53 72 45 84 12 14 12]
 [98 78 97 34 98 45 82 10 22 96]
 [21  5 25 53 99  9  6 62 75  2]]

Minimum value: 2
Maximum value: 99


In [89]:
#6
arr_zero=np.zeros(10)
arr_zero[4]=5
arr_zero

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [91]:
#7
arr_rev=[1,2,0,0,4,0]
arr_rev.reverse()
arr_rev

[0, 4, 0, 0, 2, 1]

In [99]:
#8
arr_border=np.ones((5,5))
arr_border[1:-1,1:-1]=0
arr_border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
arr_checkerboard=np.zeros((8,8))
arr_checkerboard[1::2,::2]=1
arr_checkerboard[::2,1::2]=1
arr_checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [45]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#1
arr_add=x+y
print("X + Y = ",arr_add)
arr_add=v+w
print("V + W = ",arr_add)
#2
arr_sub=x-y
print("\nX - Y = ",arr_sub)
arr_sub=v-w
print("V - W = ",arr_sub)
#3
arr_mul=x*3
print("\nX * 3 = ",arr_mul)
arr_mul=y*3
print("Y * 3 = ",arr_mul)
#4
arr_square=x**2
print("\nSquare of X = ",arr_square)
arr_square=y**2
print("Square of Y = ",arr_square)
arr_square=v**2
print("Square of V = ",arr_square)
arr_square=w**2
print("Square of W = ",arr_square)
#5
arr_dot_pro=np.dot(v,w)
print("\nDot product of V and W = ",arr_dot_pro)
arr_dot_pro=np.dot(x,v)
print("Dot product of X and V = ",arr_dot_pro)
arr_dot_pro=np.dot(x,y)
print("Dot product of X and Y = ",arr_dot_pro)

#6
arr_concat=np.concatenate((x,y),axis=0)
print("\nConcatenate X and Y along row = ",arr_concat)
arr_concat=np.concatenate((v,w))
print("Concatenate V and W along column = ",arr_concat)

#7
arr_concat=np.concatenate((x,v))
print("\nConcatenate X and V along row = ",arr_concat)
# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
# The error occurs because X is 2 dimensional array and array V has one dimension. SO in this case concatenation is not possible.

X + Y =  [[ 6  8]
 [10 13]]
V + W =  [20 22]

X - Y =  [[-4 -4]
 [-4 -3]]
V - W =  [-2 -2]

X * 3 =  [[ 3  6]
 [ 9 15]]
Y * 3 =  [[15 18]
 [21 24]]

Square of X =  [[ 1  4]
 [ 9 25]]
Square of Y =  [[25 36]
 [49 64]]
Square of V =  [ 81 100]
Square of W =  [121 144]

Dot product of V and W =  219
Dot product of X and V =  [29 77]
Dot product of X and Y =  [[19 22]
 [50 58]]

Concatenate X and Y along row =  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate V and W along column =  [ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.(A)−1 = I.
2. Prove AB != BA.
3. Prove (AB)T = (B)T(A)T

---

• Solve the following system of Linear equation using Inverse Methods.

                    2x − 3y + z = −1
                    x − y + 2z = −3
                    3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [47]:
from abc import ABC
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1 Prove A.(A)−1 != I.
A_inverse=np.linalg.inv(A)
prove_1=np.dot(A,A_inverse)
print("Prove 1.(A)−1 = I = \n",prove_1)

#2 Prove AB != BA.
AB=np.dot(A,B)
BA=np.dot(B,A)
print("\nProve 2\n",AB,"\n    != \n",BA)

#3 Prove (AB)T = (B)T(A)T
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BA_transpose = np.dot(B_transpose,A_transpose)
print("\nProve 3\n(AB)T = \n",AB_transpose)
print("\n(B)T(A)T = \n",BA_transpose)

# system of Linear equation using Inverse Methods.
# array in matrix form
N=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
P=np.array([-1,-3,9])

N_inv=np.linalg.inv(N)
X=np.dot(N_inv,P)
print("\n[ x, y, z]= ",X)




Prove 1.(A)−1 = I = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Prove 2
 [[23 13]
 [51 29]] 
    != 
 [[36 44]
 [13 16]]

Prove 3
(AB)T = 
 [[23 51]
 [13 29]]

(B)T(A)T = 
 [[23 51]
 [13 29]]

[ x, y, z]=  [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [15]:
import time
import numpy as np

# Create lists and arrays of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

# Element-wise addition using Python lists
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("Element-wise addition")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

# Element-wise multiplication using Python lists
start_time= time.time()
result_list= [x * y for x, y in zip(list1, list2)]
end_time= time.time()
print("\nElement-wise multiplication")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Element-wise multiplication using NumPy arrays
start_time= time.time()
result_array= array1 * array2
end_time= time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

# dot-product using Python lists
start_time= time.time()
result_list= [x * y for x, y in zip(list1, list2)]
end_time= time.time()
print("\nDot product")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# dot-product using NumPy arrays
start_time= time.time()
result_array= np.dot(array1, array2)
end_time= time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Element-wise addition
Time taken using Python lists: 0.08601665496826172 seconds
Time taken using NumPy arrays: 0.01013493537902832 seconds

Element-wise multiplication
Time taken using Python lists: 0.15643978118896484 seconds
Time taken using NumPy arrays: 0.0034322738647460938 seconds

Dot product
Time taken using Python lists: 0.08826732635498047 seconds
Time taken using NumPy arrays: 0.002521991729736328 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [16]:
import time
import numpy as np

# Create matrices of size 1000x1000
size = 1000
matrix1_list = [[1 for _ in range(size)] for _ in range(size)]
matrix2_list = [[2 for _ in range(size)] for _ in range(size)]
matrix1_array = np.ones((size, size))
matrix2_array = np.full((size, size), 2)

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(row_a, col_b))
                for col_b in zip(*matrix2_list)] for row_a in matrix1_list]
end_time = time.time()
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using Python lists: 114.6110987663269 seconds
Time taken using NumPy arrays: 0.08552694320678711 seconds
